### ISSUE TITLE
Link POST_schema in /services to the JSON meta-schema

### ISSUE THREAD

**Issue by MichalKononenko** [whitewhim2718/TopChef#43]
**Issue Tracking Form**

I am 

- [x] filing a bug report
- [ ] filing a feature request
- [ ] asking a question about the system

**Bug Reports**

Please state the criticality of the bug

- [ ] showstopper, stops the site from functioning
- [ ] critical, prevents a part of the site from functioning in a way that breaks the feature
- [x] annoying, mis-aligned images, bad CSS, text overflowing its container box

**Provide a description of the bug below**
Currently, the ```/services``` endpoint provides a ```meta``` dictionary, containing a ```POST_schema``` key. The schema described by this is the schema that must be satisfied in order to register a service. The ```job_registration_schema``` field's only constraint is that it matches ```"type": "object"````.

However, ```job_registration_schema``` is not just any object, it's a JSON Schema. It should therefore match the schema for a JSON schema. Fortunately, this kind of schema exists. It's called the [JSON meta-schema](http://json-schema.org/documentation.html). If this were referenced using the ```$ref``` keyword, it would be quite useful.

However, the  

**Feature Requests**

**Feature Title**

Provide a brief title for your FR. This and the issue number will be used as shorthand to work on issues.

*Title*: (Title Here)

**Description**:

(Provide a description of your feature. The more thorough, the better!)

**Dependencies**:

If your feature request depends on other issues being resolved in order to
be implemented, please write them here. Be aware that as the project changes,
we will be editing this list of issues, so that we're aware of what needs to be
done first before we can get to work on it. Ensure that your dependency list
is formatted according to the template below

```
*My issue depends on*: [#1, #2, #3]
```

*My issue depends on*:

**General Inquiries**

*Ask away! We won't bite!*

My question is: 

(question here)
